const topic = [
  {
    id: '1',
    problemsId: '',
    optionOpt: '',
    title: '当您和朋友一起用餐时，在选择餐厅或是吃什么时，你常是：',
    optionA: '决定者：意见不同时，通常都是决定者。',
    optionB: '气氛制造者：吃什么，很能带动情绪气氛。',
    optionC: '附和者：随便、没意见。',
    optionD: '意见提供者：常去否定别人之提议，自己却又没意见，不做决定。',
  },
  {
    id: '2',
    problemsId: '',
    optionOpt: '',
    title: '当您买衣服时，您是：',
    optionA: '不易受售货员之影响，“心中自有定见”。',
    optionB: '售货员的亲切友好的感受，常会促进您的购买。',
    optionC: '找熟悉的店购买。',
    optionD: '品质与价钱是否成比例，价钱是否合理。',
  },
  {
    id: '3',
    problemsId: '',
    optionOpt: '',
    title: '您的消费习惯是：',
    optionA: '找到要买的东西，付钱走人。',
    optionB: '很随意的逛，不特定买什么。',
    optionC: '有一定的消费习惯，时间不太喜欢变化。',
    optionD: '较注意东西好不好，较有成本观念。',
  },
  {
    id: '4',
    problemsId: '',
    optionOpt: '',
    title: '您的朋友，以一句话来形容您，他们会说：',
    optionA: '独断专行。',
    optionB: '热情洋溢。',
    optionC: '温和斯文。',
    optionD: '要求完美。',
  },
  {
    id: '5',
    problemsId: '',
    optionOpt: '',
    title: '您自认那一种形容，最能表现您的特色：',
    optionA: '果敢的、能接受挑战。',
    optionB: '生动活泼，不拘礼。',
    optionC: '爱倾听，喜欢稳定。',
    optionD: '处世谨慎小心，重数据分析。',
  },
  {
    id: '6',
    problemsId: '',
    optionOpt: '',
    title: '您觉得做事的重点，应该是：',
    optionA: 'what，做什么，重结果。',
    optionB: 'who，谁来做，重感受（过程）。',
    optionC: 'how，怎么做，重执行。',
    optionD: 'why，为何做，重品质。',
  },
  {
    id: '7',
    problemsId: '',
    optionOpt: '',
    title: '与同事有意见冲突（或不同）时，您是：',
    optionA: '说服对方，听从自己的意见。',
    optionB: '找其他同事或上司之意见，寻求支持。',
    optionC: '退让，以和为贵。',
    optionD: '与冲突者协调，找寻最好的意见。',
  },
  {
    id: '8',
    problemsId: '',
    optionOpt: '',
    title: '什么样的工作环境，最能鼓舞您：',
    optionA: '能让您决定事情，具领导地位的。',
    optionB: '同事相处愉快，处处受欢迎。',
    optionC: '稳定中求发展。',
    optionD: '认品质，重效率的工作。',
  },
  {
    id: '9',
    problemsId: '',
    optionOpt: '',
    title: '以下的沟通方式，那一项最符合您：',
    optionA: '直截了当，较权威式的。',
    optionB: '表情丰富，肢体语言较多。',
    optionC: '先听听别人意见，而后温和的表达自己的意见。',
    optionD: '不露感情的，理多于情，爱分析，较冷静。',
  },
  {
    id: '10',
    problemsId: '',
    optionOpt: '',
    title: '在每一次讨论问题时，您所扮演的角色为何：',
    optionA: '据理力争。',
    optionB: '协调者。',
    optionC: '赞同多数。',
    optionD: '分析问题以供大家参考。',
  },
  {
    id: '11',
    problemsId: '',
    optionOpt: '',
    title: '哪项最符合您：',
    optionA: '我做事一向以具体，短期能达到目标；决定快速，立即得到结果。',
    optionB: '在本性上我喜欢跟人交往，各式各样的人都行，甚至陌生人也行。',
    optionC: '我不喜欢强出头，宁可当候补。',
    optionD: '我是一个自我约束，很守纪律的人，凡事依既定目标行事。',
  },
  {
    id: '12',
    problemsId: '',
    optionOpt: '',
    title: '哪项最符合您：',
    optionA: '我喜欢有变化、有力激烈的、竞争的，是个可接受挑战的人。',
    optionB: '我喜欢社交，也喜欢款待人。',
    optionC: '我喜欢成为小组的一份子，固守一般性的程序。',
    optionD: '我会花很多时间去研究事与人。',
  },
  {
    id: '13',
    problemsId: '',
    optionOpt: '',
    title: '哪项最符合您：',
    optionA: '我喜欢按自己的方式做事，不在乎别人对我的观感，只是成功。',
    optionB: '有人跟我意见不一致时，我会很难过（困扰）。',
    optionC: '我知道做些改变是有必要的，但即使如此我还是觉得少冒险来的好。',
    optionD: '我对自己及他人的期望提高，这些都是为了符合我的高标准。',
  },
  {
    id: '14',
    problemsId: '',
    optionOpt: '',
    title: '哪项最符合您：',
    optionA: '我擅长于处理棘手的问题。',
    optionB: '我是个很热心的人，我喜欢跟别人工作。',
    optionC: '我喜欢听而不喜欢说话，我一开口都说得很委婉温和。',
    optionD: '处理事我较不动感情，是就是，不把感情牵扯推来，也较少与人闲聊。',
  },
  {
    id: '15',
    problemsId: '',
    optionOpt: '',
    title: '哪项最符合您：',
    optionA: '我喜欢有竞争，有竞争才能把潜能完全发挥出来。',
    optionB: '我较感性，与人相处，处事较不注意细节。',
    optionC: '我是个天生的组员，顺着群众。',
    optionD: '对事我喜欢去研究，重视证据与保证。',
  },
  {
    id: '16',
    problemsId: '',
    optionOpt: '',
    title: '哪项最符合您：',
    optionA: '我喜欢能力与权威，这是我想要的。',
    optionB: '我有时候很情绪化，一旦生气都气过头，有时置身于有趣事务中，往往无法掌握时间。',
    optionC: '我喜欢按部就班，稳扎稳打，慢慢地做事而不喜欢破釜沉舟。',
    optionD: '我很注重事务和与人的细节。',
  },
  {
    id: '17',
    problemsId: '',
    optionOpt: '',
    title: '哪项最符合您：',
    optionA: '对直接关系的环境，我有倾向喜欢去掌握及支配他人。',
    optionB: '在团体中我喜欢打成一片，活活泼泼有气氛，有感情的相处。',
    optionC: '我较遵守传统的步骤做事，不喜欢有大变化。',
    optionD: '在没有掌握事实的真相，更多资料之前我宁可保持现状。',
  },
  {
    id: '18',
    problemsId: '',
    optionOpt: '',
    title: '哪项最符合您：',
    optionA: '我在与人沟通时，直截了当的说，不喜欢兜圈子。',
    optionB: '我喜欢帮助别人，相亲相爱。',
    optionC: '我不喜欢多变化的环境，而要稳定安全的生活方式。',
    optionD: '凡事我要求的是准确无误，高品质，高标准的处事原则。',
  },
  {
    id: '19',
    problemsId: '',
    optionOpt: '',
    title: '哪项最符合您：',
    optionA: '我不喜欢别人逗我开心，不喜欢太多话的人。',
    optionB: '我喜欢参加团体活动，因为与多数人在一起很好。',
    optionC: '对事情我没有太多要求与意见，喜欢静静的有耐心的做。',
    optionD: '我做事要有一套经过计划设计的标准作业程序，来引导作业方向。',
  },
  {
    id: '20',
    problemsId: '',
    optionOpt: '',
    title: '哪项最符合您：',
    optionA: '我讨厌别人告诉我事情该如何做，因为我自有一套，我不喜欢被别人支配。',
    optionB: '我是个生气勃勃外向的人，别人爱跟我一起工作，因为别人跟我在一起工作。我会激起热心，我就是有那个能耐。',
    optionC: '我喜欢独处，与人生活在一起会注意尽量不去打扰他人居家生活。',
    optionD: '我很少加入别人的闲聊中，当话题有趣时，我会找更多的资料，小心的推进交往策略。',
  },
];
export default topic;
