/**
 * 随商
 */
// let bu = "https://demo.mallsuite.cn";
// // let auth = "https://zc-auth.zcskjy.com"
// let shareu = "https://p.shopsuite.cn/zhongcaiedu"

/**
 * 测试
 */
let bu = 'https://shop-qa.zcskjy.com';

/**
 * 生产
 */
// let bu = 'https://shop.zcskjy.com';

let auth = bu + '/zc-auth';
let shareu = bu;
let news = bu + '/zc-news';
let zcpush = bu + '/zc-push';
let zcconfig = bu + '/zc-config';
let zcselfstock = bu + '/zc-selfstock'
// 自选股票
let pathUrl = zcselfstock + '/v1/selfStock/ocrByTx'
//发现模块、小鹅登录
// let bu = "https://zc-auth.zcskjy.com";
// bu = "http://localhost:8201";
let iu = bu + '/index.php';
let au = bu + '/account.php';
let mu = bu + '/admin.php';

let su = bu + '/shop/static/src/default';
let cdn = 'https://static.shopsuite.cn';

let ip = bu + '/mobile/';
let wx = bu + '/zc-wx/';
// let ip = '/mobile/'
// let ip = 'https://demo.mallsuite.cn/mobile/'

export default {
	basePath: au,
	fileBasePath: bu,

	storeId: 1001,

	SiteUrl: shareu,
	ApiUrl: bu,
	pagesize: 10,
	WapSiteUrl: bu + '/wap',
	AppDownloadUrl: bu + '/index.php?ctl=Mobile&met=download',

	WapStaticUrl: bu + '/wap',

	SiteLogo: bu + '/image.php/shop/data/upload/media/user/10001/image/20181106/1541507399271557.png',
	SiteIcon: bu + '/image.php/shop/data/upload/media/user/10001/image/20180828/1535448698303311.png',
	WapSiteLogo: bu + '/image.php/shop/data/upload/media/user/10001/image/20181106/1541507548407729.png',

	WechatStatus: 1,

	UPLOAD_TYPE: 'default', //aliyun


	getEuid: auth + '/v1/user/getEInfoByMallId',
	xeLogin: auth + '/v1/user/xeLogin',
	liveList: auth + '/v1/live/getList',
	getListByTeacherId: auth + '/v1/live/getListByTeacherId',
	// 获取老师的直播列表：
	getTeacherLiveList: auth + '/v1/live/getTeacherLiveList',
	
	onelogin: ip + 'account/login/oneLogin',
	panzhongbaoList: news + '/v1/cls/list',
	tuyereList: news + '/v1/pamir/list',
	tuyereFreeList: news + '/v1/pamir/freeList',
	panoSelectedList: news + '/v1/cls/selected/list',
	tuyereSelectedList: news + '/v1/pamir/topETFList',
	getStocksPrice: news + '/v1/stock/getStocksPrice',
	panzhongbaoDetail: news + '/v1/cls/detail',
	tuyereETFDetail: news + '/v1/pamir/detail',
	panzhongbaoShop: news + '/v1/cls/shop',
	// 扫雷宝
	slbSortStockData: zcselfstock + '/v1/selfGroup/sort', //帅选自选股数据
	marketScanner: news + '/v1/slb/marketScanner', // 市场扫描
	slbBand: news + '/v1/slb/slbBand', // 红黑榜
	createGroup: zcselfstock + '/v1/selfGroup/create', // 创建组
	slbStock: zcselfstock + '/v1/selfGroup/queryAllStocks', //自选股票查询 
	slbFindOtherData: news + '/v1/slb/selfStockScannerDetail', // 根据自选股票查找分数等数据 http://172.16.10.79:8090
	createStock: zcselfstock + '/v1/selfGroup/create', // 添加股票
	deleteStock: zcselfstock + '/v1/selfGroup/delete', // 删除自选股
	getStockInfo: news + '/v1/slb/getStockInfo', // 股票搜索
	stockScannerDetail: news + '/v1/slb/stockScannerDetail', // 详情
	getStockRiskTypeCount: news + '/v1/slb/getStockRiskTypeCount', // 详情
	selfShock: pathUrl, //自选
	slbDescribe: news + '/v1/slb/slbRiskDesc', //扫雷宝说明
	// 事件宝
	futureBigEvent: news + '/v1/sjb/futureEvents/detail',
	eventList: news + '/v1/sjjj/getRelateStocks',
	panMouthList: news + '/v1/sjb/industryChange/detail',
	panMouthDetail: news + '/v1/sjb/industryChange/detailDesc',
	selfStockList: news + '/v1/sjb/industryChange/stockDetail',
	getCsTab: news + '/v1/chunshi/getAuthList',
	getCsVideoList: news + '/v1/chunshi/getVideoList',
	getPsVideoList: news + '/v1/pushi/getVideoList',
	getPsisInWhiteList: news + '/v1/pushi/isInWhiteList',
	
	PZBUserBinding: zcpush + '/v1/push/query', //查询用户绑定情况
	PZBoperate: zcpush + '/v1/push/operate', // 开/关推送
	// 圈子
	circleTeacher: zcconfig + '/v1/teacher/getTeacherInfo',
	// 老师列表
	teacherListDate: zcconfig + '/v1/teacher/list',

	// 活动
	mobileSave: bu + '/zc-config/v1/phone/save',
	// 老师列表
	teacherListDate: zcconfig + '/v1/teacher/list',
	shareWeixin: bu + '/zc-config/v1/weixin/getWxULink',
	userAuthList: news + '/v1/cls/userAuthList',
	//  学习-讲师详情
	getTeacherInfo: bu + '/zc-config/v1/teacher/getTeacherInfo',

	CONFIG: {
		base_url: bu,
		index_url: iu,
		admin_url: mu,
		index_page: 'index.php',
		static_url: cdn + '/shop/static/src/default',
		xhp_url: cdn + '/xhp',
	},

	HTTPS: 1,
	SYS_TYPE: 'multi',
	MULTISHOP_ENABLE: 1,
	EVALUATION_ENABLE: 1,
	SAAS_STATUS: 0,
	STORE_ID: 1001,
	VIRTUAL_ENABLE: 0,
	O2O_ENABLE: 1,
	CHAIN_ENABLE: 1,

	POINTS_VAUE_RATE: 1,
	SP_VAUE_RATE: 1,

	PLANTFORM_FX_ENABLE: 1,
	STORE_FX_ENABLE: 0,
	PLANTFORM_SP_PRIZE_ENABLE: 0,

	PLANTFORM_FX_AGENT_ENABLE: 0,
	PLANTFORM_FX_PT_ENABLE: 0,
	PLANTFORM_FX_WESTORE_ENABLE: 0,
	PLANTFORM_DELIVERY_TIME_ENABLE: 0,

	STORE_SUPPLIER_ENABLE: 1,
	PLANTFORM_REBATE_ENABLE: 0,

	PAOTUI_ENABLE: 1,
	USERSTOCK_ENABLE: 0,
	ORDERCONFIRM_ENABLE: 1,
	MARKETORDER_ENABLE: 1,

	REDPACKET_ENABLE: 0,
	CREDIT_ENABLE: 0,
	POINT_ENABLE: 1,
	SP_ENABLE: 0,

	EXCHANGECARD_ENABLE: 0,
	MONEY_TRANSFER_ENABLE: 0,

	SNS_ENABLE: 0,
	IM_ENABLE: 1,
	SUBSITE_ENABLE: 0,
	LANG_ENABLE: 0,
	FORCE_BIND_MOBILE: 0,
	SCAN_ENABLE: 0,

	CACHE: false,
	CACHE_EXPIRE: 3600 * 1,

	//暴露出去 news
	newsUrlStr: news,
	//苹果内购
	applePay: ip + '/pay/index/applePay',

	// that.Config.URL.newsUrl.newslist,
	URL: {
		newsUrl: {
			newslist: news + '/v1/news/list?',
			videolist: news + '/v1/video/list?',
			calendarlist: news + '/v1/news/calendar/list?',
			eventlist: news + '/v1/news/calendar/event/list?',
			holidaylist: news + '/v1/news/calendar/holiday/list?',
			newsdetail: news + '/v1/news/detail?',
			videodetail: news + '/v1/video/detail?',
			incidental_validate: news + '/v1/news/incidental/validate?',
			incidental_operate: news + '/v1/news/incidental/operate?',
			getUserEnableCount: news + '/v1/slb/getUserEnableCount?', // 避雷宝-未购买用户询剩余次数
			futureEventsList: news + '/v1/sjb/futureEvents/list?', // 未来大事
			
			getNewsDetail: news + '/v1/sjjj/getNewsDetail?', // 事件掘金文章详情
			
			freeList: news + '/v1/pamir/freeList?', // 机构掘金的免费列表
			
			payList: news + '/v1/pamir/list?', // 机构掘金的免费列表
			
			
			topShouYiList: news + '/v1/pamir/topShouYiList?', // 机构掘金：最新战绩
			
		
		

		},
		// that.Config.URL.config.qrCode,
		config: {
			switchquery: zcconfig + '/v1/switch/query?',
			qrCode: zcconfig + '/v1/qrCode/query?',
			guideList: zcconfig + '/v1/adConfig/list?',
			getLeastVersion: zcconfig + '/v1/appUpgrade/getLeastVersion',
			slbConfig: zcconfig + '/v1/adConfig/slbConfig?',
			miniConfig: zcconfig + '/v1/weixin/getDefault1V1',
		},
		
		getTeacherLiveList: auth + '/v1/live/getTeacherLiveList',
		getTeacherMediaList: auth + '/v1/mall/getTeacherMediaList',
		
		index: iu + '?ctl=Mobile&met=mobile&typ=json',
		index_mobile: iu + '?ctl=Mobile&met=mobile&typ=json',
		// "index_app": iu + "?ctl=Mobile&met=app&typ=json",
		index_app: ip + 'shop/mobile/app',
		// "index_guide": iu + "?ctl=Mobile&met=guide&typ=json",
		index_guide: ip + 'admin/admin-base-menu/guide',
		// "center_menu": iu + "?ctl=Mobile&met=userCenterMenu&typ=json",
		center_menu: ip + 'admin/admin-base-menu/userCenterMenu',
		story_category: iu + '?ctl=Mobile&met=storyCategory&typ=json',
		// "subsite_list": iu + "?ctl=Mobile&met=getSubsite&typ=json",
		subsite_list: ip + 'shop/mobile/getSubsite',
		// "upload": iu + "?ctl=Media&met=uploadImage&typ=json",
		upload: ip + 'admin/oss/upload',
		// "upload_file": iu + "?ctl=Media&met=uploadFile&typ=json",
		upload_file: ip + 'admin/oss/upload',
		WXSignature: wx + 'v1/official/getSignature',
		getSignature: wx + 'v1/applet/getSignature',
		appletMarkingLogin: ip + 'account/login/AppletMarkingLogin',
		isHasVoucher: ip + 'shop/userVoucher/isHasVoucher',
		upload_scrawl: iu + '?ctl=Media&met=uploadScrawl&typ=json',
		upload_config: iu + '?ctl=Media&met=config&typ=json',
		uptoken: iu + '?ctl=Media&met=uptoken&typ=json',
		info: ip + 'account/config/info',
		// "info":iu + "?ctl=Mobile&met=info&typ=json",
		listTranslateLang: ip + 'account/config/listTranslateLang',
		update_app: iu + '?ctl=Mobile&met=updateApp&typ=json',
		category_mobile_nav: ip + 'shop/mobile/getCategoryMobileNav',
		page: iu + '?ctl=Page&met=get&typ=json',
		// "minipage": iu + "?ctl=Page&met=getMiniPage&typ=json",
		minipage: ip + 'shop/page/getMiniPage',
		survey: iu + '?ctl=Page&met=doSurvey&typ=json',
		qrcode: bu + '/shop/api/qrcode.php',
		getAppDistrict: ip + 'shop/shop-base-district/getAppDistrict',
		// "getAppDistrict":iu + "?ctl=Mobile&met=getAppDistrict&typ=json",
		// "filter_opt":iu + "?ctl=Mobile&met=getFilterOpt&typ=json",
		filter_opt: ip + 'shop/store/getFilterOpt',

		// "productfilter_opt": iu + "?ctl=Mobile&met=getFilterProdcutOpt&typ=json",
		productfilter_opt: ip + 'shop/shop-product-base/getFilterProdcutOpt',
		product: {
			// "item":iu + "?ctl=Product&met=item&typ=json",
			item: ip + 'shop/shop-product-item/item',
			quick: iu + '?ctl=Product&met=quick&typ=json',
			info: iu + '?ctl=Product&met=info&typ=json',
			lists: iu + '?ctl=Product&met=lists&typ=json',
			auto_complete: iu + '?ctl=Product&met=listName&typ=json',
			// "shipping_district": iu + "?ctl=Product&met=shippingDistrict&typ=json",
			shipping_district: ip + 'shop/shop-product-base/shippingDistrict',
			// "category":iu + "?ctl=Product&met=category&typ=json",
			category: ip + 'shop/shop-base-product-category/category',
			// "brand": iu + "?ctl=Product&met=brand&typ=json",
			brand: ip + 'shop/shop-product-base/brand',
			list_brands: iu + '?ctl=Product&met=listsBrands&typ=json',
			list_brands_products: iu + '?ctl=Product&met=listsBrandsAndProducts&typ=json',
			// "product_comment":iu + "?ctl=Product&met=comment&typ=json",

			product_comment: ip + 'shop/shop-product-comment/comment',
			add_comment_reply: iu + '?ctl=Product&met=addCommentReply&typ=json',
			comment_helpful: iu + '?ctl=Product&met=commentHelpful&typ=json',
			faq: iu + '?ctl=Product&met=faq&typ=json',
			popular: iu + '?ctl=Product&met=productPopular&typ=json',
			spec: iu + '?ctl=Product&met=getSpec&typ=json',

			list_stores: iu + '?ctl=PlanformActivity&met=listsStores&typ=json',
			list_stores_products: iu + '?ctl=PlanformActivity&met=listsStoresProducts&typ=json',
			/*"list_brands":iu + "?ctl=PlanformActivity&met=listsBrands&typ=json",
			"list_brands_products":iu + "?ctl=PlanformActivity&met=listsStoresProducts&typ=json",*/
			// "list_times": iu + "?ctl=PlanformActivity&met=listsTimes&typ=json",
			list_times: ip + 'shop/Activity/listsTimes',
			list_times_products: iu + '?ctl=PlanformActivity&met=listsTimeProduct&typ=json',
			getProductOne: ip + 'shop/shop-product-base/getProduct',
			getProductDetail: ip + 'shop/shop-product-detail/getProductDetail',
		},
		loginInfo: iu + '?ctl=Index&met=getLoginInfo&typ=json',
		//"search_filter": iu + "?ctl=Mobile&met=getSearchFilter&typ=json",
		search_filter: ip + 'shop/shop-product-base/getSearchFilter',
		district: iu + '?ctl=Mobile&met=district&typ=json',
		district_all: iu + '?ctl=Mobile&met=getAllDistrict&typ=json',
		district_id: iu + '?ctl=Mobile&met=getDistrictByName&typ=json',
		search_hot_info: ip + 'shop/mobile/getSearchInfo',
		// "search_hot_info": iu + "?ctl=Mobile&met=getSearchInfo&typ=json",
		connect: ip + 'account/login/getConnectInfo',
		login_box: au + '?ctl=Login&met=index&typ=e&login_box=1',
		// "set_pwd": au + "?ctl=Login&met=setNewPassword&typ=json",
		set_pwd: ip + 'account/login/setNewPassword',
		login: ip + 'account/login/doLogin',
		loginCCB: ip + 'account/ccb/doLoginByCCB',
		// "login":au + "?ctl=Login&met=doLogin&typ=json",
		register: ip + 'account/login/register',
		// "register": au + "?ctl=Login&met=doRegister&typ=json",
		// "doSmsLogin": au + "?ctl=Login&met=doSmsLogin&typ=json",
		doSmsLogin: ip + 'account/login/doSmsLogin',
		// "logout": au + "?ctl=Login&met=logout&typ=json",
		logout: ip + 'account/login/doLogout',
		doCancel: ip + 'account/login/doCancel',
		check_mobile_or_email: au + '?ctl=Login&met=checkMobileOrEmail&typ=json',
		// "protocol": au + "?ctl=Login&met=protocol&typ=json",
		protocol: ip + 'account/login/protocol',
		check_login: au + '?ctl=Login&met=checkLogin&typ=json',
		// "check_islogin": au + "?ctl=Login&met=ifLogin&typ=json",
		check_islogin: ip + 'account/login/ifLogin',

		//"do_app_login": au + "?ctl=Login&met=doAppConnectLogin&typ=json&flag=app",
		do_app_login: ip + 'account/login/doAppConnectLogin',

		check_app_login: au + '?ctl=Login&met=checkAppConnectLogin&typ=json&flag=app',
		// "get_miniapp_open_id": au + "?ctl=Login&met=getOpenIdByCode&typ=json",
		get_miniapp_open_id: ip + 'account/weiXin/getOpenIdByCode',

		autoLoginAndOffer: ip + 'account/autoLogin/autoLoginAndOffer',



		register_wechat_account: au + '?ctl=Login&met=doRegisterWechatAccount&typ=json',
		find_pwd_s2: au + '?ctl=Login&met=findpwdStepTwo&typ=e&step=2',
		find_pwd_s3: au + '?ctl=Login&met=findpwdStepThree&typ=e&step=3',
		delivery_info: bu + '/shop/api/delivery.php',
		download_proxy: 'https://test.suteshop.com/shop/api/download.php',
		account: {
			// "certificate": au + "?ctl=User_Security&met=certification&typ=e",
			certificate: ip + 'account/userSecurity/certification',
			typeList: au + '?ctl=User_Account&met=getUserType&typ=e',
			get_mobile_info: au + '?ctl=User_Security&met=index&typ=json',
			check_mobile_code: au + '?ctl=User_Security&met=checkMobile&typ=json',
			// "get_mobile_checkcode": au + "?ctl=VerifyCode&met=mobile&typ=json",
			get_mobile_checkcode: ip + 'account/user/verifyCode',
			// "get_email_checkcode": au + "?ctl=VerifyCode&met=email&typ=json",
			get_email_checkcode: ip + 'account/user/verifyCode',
			check_security_change: au + '?ctl=User_Security&met=checkSecurityChange&typ=json',
			reset_password: au + '?ctl=User_Security&met=resetPassword&typ=json',
			// "bind_mobile": au + "?ctl=User_Security&met=bindMobile&typ=json",
			bind_mobile: ip + 'account/userSecurity/bindMobile',
			// "commit_certificate": au + "?ctl=User_Security&met=saveCertificate&typ=json",
			commit_certificate: ip + 'account/userSecurity/saveCertificate',
			certified_member: au + '?ctl=User_Security&met=certifiedSns&typ=json',
			change_password: au + '?ctl=User_Security&met=changePassword&typ=json',
			// "edit_user_info": au + "?ctl=User_Account&met=edit&typ=json",
			edit_user_info: ip + 'account/user/edit',
			edit_user_sign: au + '?ctl=User_Account&met=sign&typ=json',
			get_card_qrcode: au + '?ctl=User_Account&met=getCardQrcode&typ=e',
		},
		wx: {
			share: au + '?ctl=Connect_Weixin&met=share&typ=e',
			// "config": au + "?ctl=Connect_Weixin&met=wxConfig&typ=e&body_class_none=1",
			config: ip + 'account/weiXin/wxConfig',
			pay_config: au + '?ctl=Connect_Weixin&met=wxPayConfig&typ=json',
			//"mplogin": au + "?ctl=Connect_Weixin&met=login&typ=e&flag=mp",
			mplogin: ip + 'account/weiXin/redirectToWxCode',
			openlogin: au + '?ctl=Connect_Weixin&met=login&typ=e&flag=open',
			// "applogin": au + "?ctl=Connect_Weixin&met=jscode2session&typ=json&flag=app",
			applogin: ip + 'account/weiXin/jsCode2Session',
			// "editinfo": au + "?ctl=Connect_Weixin&met=jscode2session&typ=json&flag=app",
			editinfo: ip + 'account/weiXin/jsCode2Session',
			// "checkAppLogin": au + "?ctl=Connect_Weixin&met=checkAppLogin&typ=json&flag=app",
			checkAppLogin: ip + 'account/weiXin/checkAppLogin',
			getQRCode: au + '?ctl=Connect_Weixin&met=getQRCode&typ=json&flag=app',
			getMiniAppQRCode: au + '?ctl=Connect_Weixin&met=getMiniAppQRCode&typ=json&flag=app',
			getMiniAppQRCodeUnlimit: au + '?ctl=Connect_Weixin&met=getMiniAppQRCodeUnlimit&typ=json&flag=app',
			getMiniAppQRCodeUnlimitPoster: au +
				'?ctl=Connect_Weixin&met=getMiniAppQRCodeUnlimitPoster&typ=json&flag=app',
			pay: bu + '/account/modules/pay/api/payment/wx/pay.php',
			get_tpl_msg_config: au + '?ctl=Connect_Weixin&met=getTmpMsgConfig&typ=json&flag=app',
			send_tpl_msg: au + '?ctl=Connect_Weixin&met=sendTplMsg&typ=json&flag=app',
		},
		store: {
			get: iu + '?ctl=Store&met=get&typ=json',
			// "add": iu + "?ctl=Store&met=add&typ=json",
			add: ip + 'shop/store/add',
			credit: iu + '?ctl=Store&met=credit&typ=json',
			// "info":iu + "?ctl=Store&met=info&typ=json",
			info: ip + 'shop/store/info',
			// "contents":iu + "?ctl=Store&met=contents&typ=json",
			contents: ip + 'shop/store/contents',
			// "index_diy": iu + "?ctl=Store&met=indexDiy&typ=json",
			index_diy: ip + 'shop/page/index_diy',
			profile: iu + '?ctl=Store&met=profile&typ=json',
			menu: iu + '?ctl=Store&met=menu&typ=json',
			// "lists":iu + "?ctl=Store&met=lists&typ=json",
			lists: ip + 'shop/store/lists',

			listsChain: iu + '?ctl=Chain&met=lists&typ=json',
			// "getChain":iu + "?ctl=Chain&met=getChainInfo&typ=json",
			getChain: ip + 'shop/shop-chain-base/getChainInfo',
			listsChainItems: iu + '?ctl=Chain&met=listsChainItems&typ=json',
			listsChainProduct: iu + '?ctl=Chain&met=listsChainProduct&typ=json',
			listChainByItem: iu + '?ctl=Chain&met=listChainByItem&typ=json',
			// "getNearChain":iu + "?ctl=Chain&met=getNearChain&typ=json",
			getNearChain: ip + 'shop/shop-chain-base/getNearChain',

			isDefautChain: iu + '?ctl=Chain&met=isDefautChain&typ=json',
			setChain: iu + '?ctl=Chain&met=setChain&typ=json',

			near: iu + '?ctl=Store&met=lists&typ=json',
			// "category": iu + "?ctl=Store&met=category&typ=json",
			category: ip + 'shop/store/category',
			// "activity":iu + "?ctl=Store&met=activity&typ=json",
			activity: ip + 'shop/store/activity',
			// "product":iu + "?ctl=Product&met=lists&typ=json",
			product: ip + 'shop/shop-product-base/lists',
			item: iu + '?ctl=Product&met=lists&typ=json',
			// "product_category":iu + "?ctl=Store&met=productCategory&typ=json",
			product_category: ip + 'shop/store/productCategory',
			product_popular: iu + '?ctl=Store&met=productPopular&typ=json',
			lists_store_grade: iu + '?ctl=Store&met=listsStoreGrade&typ=json',
			// "lists_store_category": iu + "?ctl=Store&met=listsStoreCategory&typ=json",
			lists_store_category: ip + 'shop/store/listsStoreCategory',
			commit_payment_voucher: iu + '?ctl=Store&met=paymentVoucher&typ=json',
			survey: iu + '?ctl=Store&met=doSurvey&typ=json',
			lists_groupbuy_store: iu + '?ctl=Activity&met=listsGroupBuyStore&typ=json',
		},
		point: {
			// "voucher": iu + "?ctl=Point&met=voucher&typ=json",
			voucher: ip + 'shop/point/voucher',
			// "index": iu + "?ctl=Point&met=index&typ=json",
			index: ip + 'shop/point/index',
			product_detail: iu + '?ctl=Point&met=productDetail&typ=json',
			// "product": iu + "?ctl=Point&met=product&typ=json"
			product: ip + 'shop/point/product',
		},
		verify: {
			image: au + '?ctl=VerifyCode&met=image&typ=json',
			// "mobile": au + "?ctl=VerifyCode&met=mobile&typ=json",
			mobile: ip + 'account/user/verifyCode',
			// "email": au + "?ctl=VerifyCode&met=email&typ=json"
			email: ip + 'account/user/verifyCode',
		},
		diy: {
			fonts: iu + '?mdu=diy&ctl=Diy&met=getFonts&typ=json',
			getFonts: iu + '?mdu=diy&ctl=Diy&met=getFonts&typ=json',
			getCartFileUrl: iu + '?mdu=diy&ctl=Diy&met=getCartFileUrl&typ=json',
			getModelShowUrl: iu + '?mdu=diy&ctl=Diy&met=getModelShow&typ=json',
			getItemSkuColorShowUrl: iu + '?mdu=diy&ctl=Diy&met=getItemSkuColorShowUrl&typ=json',
			getTypeBasesByParentUrl: iu + '?mdu=diy&ctl=Diy&met=getMaterialCategory&typ=json',
			queryOriginalByCategoryUrl: iu + '?mdu=diy&ctl=Diy&met=getMaterial&typ=json',
			removeBgColor: iu + '?mdu=diy&ctl=Diy&met=removeBgColor&typ=json',
			getStyleUrl: iu + '?mdu=diy&ctl=Diy&met=getStyleUrl&typ=json',
			imgstyUrl: iu + '?mdu=diy&ctl=Diy&met=getImageStyleUrl&typ=json',
			getUserDiyGoodsSkuListUrl: iu + '?mdu=diy&ctl=Diy&met=getUserDiyGoodsSkuListUrl&typ=json',
			saveDiyGoodsAndAddShopCartUrl: iu + '?mdu=diy&ctl=Diy&met=saveDiyGoodsAndAddShopCartUrl&typ=json',
			upload: iu + '?mdu=diy&ctl=Diy&met=uploadImage&typ=json',
			upload_file: iu + '?mdu=diy&ctl=Diy&met=uploadFile&typ=json',
			upload_scrawl: iu + '?mdu=diy&ctl=Diy&met=uploadScrawl&typ=json',
			upload_scrawl_diy: iu + '?mdu=diy&ctl=Diy&met=uploadScrawlDiy&typ=json',
			upload_config: iu + '?mdu=diy&ctl=Diy&met=config&typ=json',
			uptoken: iu + '?mdu=diy&ctl=Diy&met=uptoken&typ=json',
			getDespLists: iu + '?mdu=diy&ctl=Diy&met=getDespLists&typ=json',
			buyGoodsUrl: iu + '?mdu=diy&ctl=Diy&met=buyGoodsUrl&typ=json',
			getDesignList: iu + '?mdu=diy&ctl=Diy&met=getDesignList&typ=json',
			getDiyMaskListUrl: iu + '?mdu=diy&ctl=Diy&met=getDiyMaskList&typ=json',
			getAllColorUrl: iu + '?mdu=diy&ctl=Diy&met=getAllColorUrl&typ=json',
			getTechnicsListUrl: iu + '?mdu=diy&ctl=Diy&met=getTechnicsListUrl&typ=json',
			getTechnicsPriceUrl: iu + '?mdu=diy&ctl=Diy&met=getTechnicsPriceUrl&typ=json',
			searchMaterialsUrl: iu + '?mdu=diy&ctl=Diy&met=searchMaterialsUrl&typ=json',
		},
		cart: {
			// "add": iu + "?ctl=Cart&met=add&typ=json",
			add: ip + 'shop/userCart/add',
			// "remove": iu + "?ctl=Cart&met=remove&typ=json",
			remove: ip + 'shop/userCart/remove',
			removeItems: iu + '?ctl=Cart&met=removeItems&typ=json',
			edit: iu + '?ctl=Cart&met=edit&typ=json',
			// "lists":iu + "?ctl=Cart&met=lists&typ=json",
			lists: ip + 'shop/userCart/lists',
			listsMini: iu + '?ctl=Cart&met=listsMini&typ=json',
			// "quantity": iu + "?ctl=Cart&met=editQuantity&typ=json",
			quantity: ip + 'shop/userCart/editQuantity',
			cookie: iu + '?ctl=Cart&met=getCookieCart&typ=json',
			index: iu + '?ctl=Cart&met=index&typ=json',
			// "sel": iu + "?ctl=Cart&met=sel&typ=json",
			sel: ip + 'shop/userCart/sel',
			// "checkout": iu + "?ctl=Cart&met=checkout&typ=json",
			checkout: ip + 'shop/userCart/checkout',
			checkDelivery: iu + '?ctl=Cart&met=checkDelivery&typ=json',
			order: iu + '?ctl=Cart&met=order&typ=e',
			// "getselect":iu + "?ctl=Cart&met=getselect&typ=json",
			getselect: ip + 'shop/userCart/getSelect',
			batchadd: iu + '?ctl=Cart&met=addBatch&typ=json',
		},
		cms: {
			// "lists": iu + "?mdu=cms&ctl=Article&met=lists&typ=json",
			lists: ip + 'cms/article/lists',
			category: iu + '?mdu=cms&ctl=Article&met=category&typ=json',
			// "get": iu + "?mdu=cms&ctl=Article&met=get&typ=json",
			get: ip + 'cms/article/get',
			add_article_comment: iu + '?mdu=cms&ctl=Article&met=addComment&typ=json',
			add_article_comment_reply: iu + '?mdu=cms&ctl=Article&met=addCommentReply&typ=json',
			get_related_article: iu + '?mdu=cms&ctl=Article&met=getRelatedArticle&typ=json',
			comment_helpful: iu + '?mdu=cms&ctl=Article&met=commentHelpful&typ=json',
			remove_comment_helpful: iu + '?mdu=cms&ctl=Article&met=removeCommentHelpful&typ=json',
			comment_reply_helpful: iu + '?mdu=cms&ctl=Article&met=commentReplyHelpful&typ=json',
			remove_comment_reply_helpful: iu + '?mdu=cms&ctl=Article&met=removeCommentReplyHelpful&typ=json',
		},
		user: {
			overview: ip + 'account/user/overview',
			cart_count: iu + '?ctl=User_Account&met=getCartNum&typ=json',
			// "msg_count": au + "?mdu=sns&ctl=User_Message&met=getMsgCount&typ=json",
			msg_count: ip + 'sns/userMessage/getMsgCount',
			// "msg_config": au + "?ctl=Index&met=getConfig&typ=json",
			msg_config: ip + 'sns/im/getImConfig',
			//"kefu_config": au + "?ctl=Index&met=getKefuConfig&typ=json",
			kefu_config: ip + 'sns/im/getKefuConfig',
			// "msg_lists": au + "?mdu=sns&ctl=User_Message&met=lists&typ=json",
			msg_lists: ip + 'sns/userMessage/lists',
			// "msg_chat_lists": au + "?mdu=sns&ctl=User_Message&met=listChatMsg&typ=json",
			msg_chat_lists: ip + 'sns/userMessage/listChatMsg',
			// "msg_get": au + "?mdu=sns&ctl=User_Message&met=get&typ=json",
			msg_get: ip + 'sns/userMessage/get',
			// "msg_set_read": au + "?mdu=sns&ctl=User_Message&met=setRead&typ=json",
			msg_set_read: ip + 'sns/userMessage/setRead',
			zonemsg_lists: au + '?mdu=sns&ctl=User_ZoneMessage&met=lists&typ=json',
			zonemsg_add_msg: au + '?mdu=sns&ctl=User_ZoneMessage&met=addMessage&typ=json',
			msg_user_lists: au + '?mdu=sns&ctl=User_Message&met=getMsgUser&typ=json',
			// "msg_add": au + "?mdu=sns&ctl=User_Message&met=add&typ=json",
			msg_add: ip + 'sns/userMessage/add',
			msg_remove: au + '?mdu=sns&ctl=User_Message&met=remove&typ=json',
			msg_remove_user: au + '?mdu=sns&ctl=User_Message&met=removeUserMsg&typ=json',
			msg_notice_lists: au + '?mdu=sns&ctl=User_Message&met=listNotice&typ=json',
			// "lists_base_level": au + "?mdu=sns&ctl=Index&met=listBaseUserLevel&typ=json",
			lists_base_level: ip + 'account/userLevel/listBaseUserLevel',
			friend_info_lists: au + '?mdu=sns&ctl=User_Friend&met=getFriendsInfo&typ=json',
			// "friend_agree": au + "?mdu=sns&ctl=User_Friend&met=agree&typ=json",
			friend_agree: ip + 'sns/userFriend/agree',
			// "friend_refuse": au + "?mdu=sns&ctl=User_Friend&met=refuse&typ=json",
			friend_refuse: ip + 'sns/userFriend/refuse',
			more_comment: iu + '?ctl=User_Comment&met=loadMoreComment&typ=json',
			add_product_comment: iu + '?ctl=User_Comment&met=add&typ=json',
			// "add_order_comment": iu + "?ctl=User_Order&met=addOrderComment&typ=json",
			add_order_comment: ip + 'shop/userOrder/addOrderComment',
			ask_helpful: iu + '?ctl=User_Ask&met=hasHelpful&typ=json',
			ask_add: iu + '?ctl=User_Ask&met=add&typ=json',
			// "edit": iu + "?ctl=User_Account&met=edit&typ=json",
			edit: ip + 'account/user/edit',
			lists: iu + '?ctl=User_Account&met=lists&typ=json',
			// "points": iu + "?ctl=User_Resource&met=pointsHistory&typ=json",
			points: ip + 'shop/userVoucher/pointsHistory',
			money2points: iu + '?ctl=User_Resource&met=money2Points&typ=json',
			points2money: iu + '?ctl=User_Resource&met=points2Money&typ=json',
			// "listsExp": iu + "?ctl=User_Resource&met=listsExp&typ=json",
			listsExp: ip + 'shop/userResource/listsExp',
			// "listsExpRule": iu + "?ctl=User_Resource&met=listsExpRule&typ=json",
			listsExpRule: ip + 'pay/userResource/listsExpRule',
			// "signState": iu + "?ctl=User_Resource&met=signState&typ=json",
			signState: ip + 'pay/userResource/signState',
			resource: iu + '?ctl=User_Resource&met=resource&typ=json',
			// "signIn": iu + "?ctl=User_Resource&met=signIn&typ=json",
			signIn: ip + 'pay/userResource/signIn',
			lists_chain_code: iu + '?ctl=User_Resource&met=listsChainCode&typ=json',
			lists_voucher_product: iu + '?ctl=User_Voucher&met=listsVoucherProduct&typ=json',
			// "voucherList": iu + "?ctl=User_Voucher&met=lists&typ=json",
			voucherList: ip + 'shop/userVoucher/lists',
			// "voucher_get": iu + "?ctl=Activity&met=getVoucher&typ=json",
			voucher_get: ip + 'shop/userActivity/getVoucher',
			voucherNum: iu + '?ctl=User_Voucher&met=getVoucherNum&typ=json',
			// "eachVoucherNum": iu + "?ctl=User_Voucher&met=getEachVoucherNum&typ=json",
			eachVoucherNum: ip + 'shop/userVoucher/getEachVoucherNum',
			// "voucher_add": iu + "?ctl=User_Voucher&met=add&typ=json",
			voucher_add: ip + 'shop/userVoucher/add',
			voucher_used: iu + '?ctl=User_Voucher&met=checkVoucher&typ=json',
			voucher_offline: iu + '?ctl=User_Voucher&met=addOffline&typ=json',
			receive_new_gift: iu + '?ctl=User_Voucher&met=receiveGift&typ=json',
			// "return_lists":iu + "?ctl=User_Return&met=lists&typ=json",
			return_lists: ip + 'shop/userReturn/lists',
			return_add: iu + '?ctl=User_Return&met=add&typ=json',
			// "return_add_one": iu + "?ctl=User_Return&met=addItem&typ=json",
			return_add_one: ip + 'shop/userReturn/addItem',
			// "return_item": iu + "?ctl=User_Return&met=returnItem&typ=json",
			return_item: ip + 'shop/userReturn/returnItem',
			// "return_cancel": iu + "?ctl=User_Return&met=cancel&typ=json",
			return_cancel: ip + 'shop/userReturn/cancel',
			// "return_get": iu + "?ctl=User_Return&met=get&typ=json",
			return_get: ip + 'shop/userReturn/get',
			// "return_tracking":iu + "?ctl=User_Return&met=returnTrackingNumber&typ=json",
			return_tracking: ip + 'shop/userReturn/returnTrackingNumber',
			return_confirm_refund: iu + '?ctl=User_Return&met=confirmRefund&typ=json',
			invoice_type: iu + '?ctl=User_Invoice&met=type&typ=json',
			// "invoice_lists": iu + "?ctl=User_Invoice&met=lists&typ=json",
			invoice_lists: ip + 'shop/userInvoice/lists',
			// "invoice_add": iu + "?ctl=User_Invoice&met=add&typ=json",
			invoice_add: ip + 'shop/userInvoice/add',
			// "invoice_edit": iu + "?ctl=User_Invoice&met=edit&typ=json",
			invoice_edit: ip + 'shop/userInvoice/edit',
			// "invoice_get": iu + "?ctl=User_Invoice&met=get&typ=json",
			invoice_get: ip + 'shop/userInvoice/get',
			// "invoice_remove": iu + "?ctl=User_Invoice&met=remove&typ=json",
			invoice_remove: ip + 'shop/userInvoice/remove',
			add_point_shopping_order: iu + '?ctl=User_Order&met=addPointShoppingOrder&typ=json',
			// "order_add": iu + "?ctl=User_Order&met=add&typ=json",
			order_add: ip + 'shop/userOrder/add',
			// "order_lists":iu + "?ctl=User_Order&met=lists&typ=json",
			order_lists: ip + 'shop/userOrder/lists',
			// "order_cancel": iu + "?ctl=User_Order&met=cancel&typ=json",
			order_cancel: ip + 'shop/userOrder/cancel',
			// "order_receive": iu + "?ctl=User_Order&met=receive&typ=json",
			order_receive: ip + 'shop/userOrder/receive',
			order_remove: iu + '?ctl=User_Order&met=remove&typ=json',
			// "order_detail":iu + "?ctl=User_Order&met=detail&typ=json",
			order_detail: ip + 'shop/userOrder/detail',

			order_delivery: iu + '?ctl=User_Order&met=delivery&typ=json',
			order_index: iu + '?ctl=User_Order&met=index&typ=e',
			order_comment_manage: iu + '?ctl=User_Order&met=storeCommentManage&typ=json',
			// "order_comment_with_content": iu + "?ctl=User_Order&met=storeEvaluationWithContent&typ=json",
			order_comment_with_content: ip + 'shop/userOrder/storeEvaluationWithContent',
			order_comment_add: iu + '?ctl=User_Order&met=addOrderComment&typ=json',
			wish_store_lists: ip + 'shop/favorites/lists?action=store',
			wish_item_lists: ip + 'shop/favorites/lists?action=item',
			wish_brand_lists: ip + 'shop/favorites/lists?action=brand',
			wish_store_get: iu + '?ctl=User_Favorites&met=get&typ=json&action=store',
			wish_item_get: iu + '?ctl=User_Favorites&met=get&typ=json&action=item',
			wish_brand_get: iu + '?ctl=User_Favorites&met=get&typ=json&action=brand',
			// "wish_store_remove": iu + "?ctl=User_Favorites&met=remove&typ=json&action=store",
			wish_store_remove: ip + 'shop/favorites/remove?action=store',
			// "wish_item_remove": iu + "?ctl=User_Favorites&met=remove&typ=json&action=item",
			wish_item_remove: ip + 'shop/favorites/remove?action=item',
			// "wish_brand_remove": iu + "?ctl=User_Favorites&met=remove&typ=json&action=brand",
			wish_brand_remove: ip + 'shop/favorites/remove?action=brand',
			// "wish_store_add": iu + "?ctl=User_Favorites&met=add&typ=json&action=store",
			wish_store_add: ip + 'shop/favorites/add?action=store',
			// "wish_item_add": iu + "?ctl=User_Favorites&met=add&typ=json&action=item",
			wish_item_add: ip + 'shop/favorites/add?action=item',
			// "wish_brand_add": iu + "?ctl=User_Favorites&met=add&typ=json&action=brand",
			wish_brand_add: iu + 'shop/favorites/add?action=brand',
			// "browser_lists":iu + "?ctl=User_Favorites&met=browser&typ=json&action=item",
			browser_lists: ip + 'shop/favorites/browser?action=item',
			browser_remove: iu + '?ctl=User_Favorites&met=removeBrowser&typ=json&action=item',
			// "feedback_add": iu + "?ctl=User_Feedback&met=add&typ=json",
			feedback_add: ip + 'shop/feedback/addFeedback',
			// "feedback_lists": iu + "?ctl=User_Feedback&met=lists&typ=json",
			feedback_lists: ip + 'shop/feedback/lists',
			// "feedback_category": iu + "?ctl=User_Feedback&met=getCategory&typ=json",
			feedback_category: ip + 'shop/feedback/getCategory',
			check_wechat_address: iu + '?ctl=User_DeliveryAddress&met=checkWeChatAddress&typ=json',
			// "address_add": iu + "?ctl=User_DeliveryAddress&met=save&typ=json",
			address_add: ip + 'shop/userDeliveryAddress/save',
			// "address_get": iu + "?ctl=User_DeliveryAddress&met=get&typ=json",
			address_get: ip + 'shop/userDeliveryAddress/get',
			// "address_edit": iu + "?ctl=User_DeliveryAddress&met=save&typ=json",
			address_edit: ip + 'shop/userDeliveryAddress/save',
			// "address_lists": iu + "?ctl=User_DeliveryAddress&met=lists&typ=json",
			address_lists: ip + 'shop/userDeliveryAddress/lists',
			// "address_remove": iu + "?ctl=User_DeliveryAddress&met=remove&typ=json",
			address_remove: ip + 'shop/userDeliveryAddress/remove',
			address_manage: iu + '?ctl=User_DeliveryAddress&met=manage&typ=e',
			// "joinIn": iu + "?ctl=Join&met=step&typ=e",
			joinIn: ip + 'shop/join/step',
			// "listsLottery": iu + "?ctl=User_Activity&met=getLottery&typ=json",
			listsLottery: ip + 'shop/userActivity/getLottery',
			// "doLottery": iu + "?ctl=User_Activity&met=doLottery&typ=json",
			doLottery: ip + 'shop/userActivity/doLottery',
			// "listsLotteryHistory": iu + "?ctl=User_Activity&met=listsLotteryHistory&typ=json",
			listsLotteryHistory: ip + 'shop/userActivity/listsLotteryHistory',
			//"getLotteryHistory": iu + "?ctl=User_Activity&met=getLotteryHistory&typ=json",
			getLotteryHistory: ip + 'shop/userActivity/getLotteryHistory',
			//"updateLotteryAddress": iu + "?ctl=User_Activity&met=updateLotteryAddress&typ=json",
			updateLotteryAddress: ip + 'shop/userActivity/updateLotteryAddress',
			// "listsMarketing": iu + "?ctl=User_Activity&met=listsMarketing&typ=json",
			listsMarketing: ip + 'shop/userActivity/listsMarketing',
			listsUserMarketing: iu + '?ctl=User_Activity&met=listsUserMarketing&typ=json',
			// "getMarketing": iu + "?ctl=User_Activity&met=getMarketing&typ=json",
			getMarketing: ip + 'shop/userActivity/getMarketing',
			doMarketing: iu + '?ctl=User_Activity&met=doMarketing&typ=json',
			// "doCutPrice": iu + "?ctl=User_Activity&met=doCutPrice&typ=json",
			doCutPrice: ip + 'shop/userActivity/doCutPrice',
			// "listsUserCutPriceHistory": iu + "?ctl=User_Activity&met=listsUserCutPriceHistory&typ=json",
			listsUserCutPriceHistory: ip + 'shop/userActivity/listsUserCutPriceHistory',
			listsCutPriceActivity: iu + '?ctl=Activity&met=listsCutPriceActivity&typ=json',
			// "getCutPriceActivity": iu + "?ctl=Activity&met=getCutPriceActivity&typ=json",
			getCutPriceActivity: ip + 'shop/userActivity/getCutPriceActivity',
			// "listsCutPriceHistory": iu + "?ctl=Activity&met=listsCutPriceHistory&typ=json",
			listsCutPriceHistory: ip + 'shop/userActivity/listsCutPriceHistory',
			listsGroupbookingActivity: iu + '?ctl=Activity&met=listsGroupbookingActivity&typ=json',
			// "listsGroupbooking": iu + "?ctl=Activity&met=listsGroupbooking&typ=json",
			listsGroupbooking: ip + 'shop/userActivity/listsGroupbooking',
			// "listsUserGroupbooking": iu + "?ctl=User_Activity&met=listsUserGroupbooking&typ=json",
			listsUserGroupbooking: ip + 'shop/userActivity/listsUserGroupbooking',
			// "getUserGroupbooking": iu + "?ctl=User_Activity&met=getUserGroupbooking&typ=json",
			getUserGroupbooking: ip + 'shop/userActivity/getUserGroupbooking',
			// "direct_store_add": iu + "?ctl=User_DistributionStoreDirectsellerProduct&met=add&typ=json",
			direct_store_add: ip + 'shop/userDistributionStoreDirectseller/add',
			direct_store_lists: iu + '?ctl=User_DistributionStoreDirectsellerProduct&met=index&typ=json',
			direct_store_remove: iu + '?ctl=User_DistributionStoreDirectsellerProduct&met=remove&typ=json',
			// "direct_store_index": iu + "?mdu=distribution&ctl=WeStore&met=index&typ=json",
			direct_store_index: ip + 'shop/webStore/index',
			listsUserVideo: iu + '?ctl=User_Order&met=listsUserVideo&typ=json',
			serviceMessage: iu + '?ctl=Info&met=index&typ=json',
			addServiceMessage: iu + '?ctl=User_Info&met=add&typ=json',
		},
		pay: {
			type: au + '?mdu=pay&ctl=Index&met=payType&typ=json',
			lists: au + '?mdu=pay&ctl=Index&met=payLists&typ=json',
			// "recharge": au + "?mdu=pay&ctl=Index&met=recharge&typ=json",
			recharge: ip + 'pay/index/recharge',
			recharge_level: au + '?mdu=pay&ctl=Index&met=rechargeByLevel&typ=json',
			// "recharge_list": au + "?mdu=pay&ctl=Index&met=listRechargeLevel&typ=json",
			recharge_list: ip + 'pay/index/listRechargeLevel',
			favorable: au + '?mdu=pay&ctl=Index&met=favorable&typ=json',
			other: au + '?mdu=pay&ctl=Index&met=other&typ=json',
			// "pay": au + "?mdu=pay&ctl=Index&met=pay&typ=json",
			pay: ip + 'pay/index/pay',
			check_pay_passwd: au + '?mdu=pay&ctl=Index&met=checkPayPasswd&typ=json',
			// "get_pay_passwd": au + "?mdu=pay&ctl=Index&met=getPayPasswd&typ=json",
			get_pay_passwd: ip + 'pay/index/getPayPasswd',
			// "asset": au + "?mdu=pay&ctl=Index&met=resourceIndex&typ=json",
			asset: ip + 'pay/index/resource',
			// "consume_record": au + "?mdu=pay&ctl=Index&met=consumeRecord&typ=json",
			consume_record: ip + 'pay/index/consumeRecord',
			get_consume_record: au + '?mdu=pay&ctl=Index&met=getConsumeRecord&typ=json',
			consume_deposit: au + '?mdu=pay&ctl=Index&met=consumeDeposit&typ=json',
			// "consume_trade": au + "?mdu=pay&ctl=Index&met=consumeTrade&typ=json",
			consume_trade: ip + 'pay/index/consumeTrade',
			consume_trade_detail: au + '?mdu=pay&ctl=Index&met=getConsumeTradeDetail&typ=json',
			// "consume_withdraw": au + "?mdu=pay&ctl=Index&met=consumeWithdraw&typ=json",
			consume_withdraw: ip + 'pay/index/consumeWithdraw',
			consume_withdraw_info: au + '?mdu=pay&ctl=Index&met=withdrawInfo&typ=json',
			// "consume_withdraw_add": au + "?mdu=pay&ctl=Index&met=addWithdraw&typ=json",
			consume_withdraw_add: ip + 'pay/index/addWithdraw',
			addCard: au + '?mdu=pay&ctl=Card&met=addCard&typ=json',
			cardHistory: au + '?mdu=pay&ctl=Card&met=cardHistory&typ=json',
			reset_paypasswd: au + '?mdu=pay&ctl=Index&met=resetPayPassword&typ=json',
			// "change_paypasswd": au + "?mdu=pay&ctl=Index&met=changePayPassword&typ=json",
			change_paypasswd: ip + 'pay/index/changePayPassword',
			receive_qrcode: au + '?mdu=pay&ctl=Index&met=receiveQrcode&typ=json',
			transfer: au + '?mdu=pay&ctl=Index&met=transfer&typ=json',
			transfer_user_row: au + '?mdu=pay&ctl=Index&met=transferUserRow&typ=json',

			// "list_user_bank": au + "?mdu=pay&ctl=Index&met=listUserBank&typ=json",
			list_user_bank: ip + 'pay/userBank/listUserBank',
			// "get_user_bank": au + "?mdu=pay&ctl=Index&met=getUserBank&typ=json",
			get_user_bank: ip + 'pay/userBank/getUserBank',
			// "add_user_bank": au + "?mdu=pay&ctl=Index&met=addUserBank&typ=json",
			add_user_bank: ip + 'pay/userBank/addOrEditUserBank',
			// "edit_user_bank": au + "?mdu=pay&ctl=Index&met=editUserBank&typ=json",
			edit_user_bank: ip + 'pay/userBank/addOrEditUserBank',
			// "remove_user_bank": au + "?mdu=pay&ctl=Index&met=removeUserBank&typ=json"
			remove_user_bank: ip + 'pay/userBank/removeUserBank',
		},
		exchange: {
			sp_exchange: au + '?mdu=exchange&ctl=Sp&met=exchange&typ=json',
			sp_transfer: au + '?mdu=exchange&ctl=Sp&met=transfer&typ=json',
			point_transfer: au + '?mdu=exchange&ctl=Sp&met=transferPoint&typ=json',
			sp_sale: au + '?mdu=exchange&ctl=Sp&met=sale&typ=json',
			sp_buy: au + '?mdu=exchange&ctl=Sp&met=buy&typ=json',
			bp_exchange: au + '?mdu=exchange&ctl=Bp&met=exchange&typ=json',
			bp_market: au + '?mdu=exchange&ctl=Bp&met=market&typ=json',
			sp_history: au + '?mdu=exchange&ctl=Sp&met=listSpHistory&typ=json',
			sp_trade: au + '?mdu=exchange&ctl=Sp&met=listSpMarket&typ=json',
			sp_trade_cancel: au + '?mdu=exchange&ctl=Sp&met=cancelSpMarket&typ=json',
			sp_trade_buy: au + '?mdu=exchange&ctl=Sp&met=buySpMarket&typ=json',
			do_sp_exchange: au + '?mdu=exchange&ctl=Sp&met=doSpExchange&typ=json',
			do_sp_transfer: au + '?mdu=exchange&ctl=Sp&met=doSpTransfer&typ=json',
			do_point_transfer: au + '?mdu=exchange&ctl=Sp&met=doPointTransfer&typ=json',
			do_sp_sale: au + '?mdu=exchange&ctl=Sp&met=doSpSale&typ=json',
			bp_history: au + '?mdu=exchange&ctl=Bp&met=listBpHistory&typ=json',
			do_bp_exchange: au + '?mdu=exchange&ctl=Bp&met=doBpExchange&typ=json',
			do_bp_market: au + '?mdu=exchange&ctl=Bp&met=doBpMarket&typ=json',
			funds_lists: au + '?mdu=exchange&ctl=Funds&met=listFunds&typ=json',
			funds_profit_lists: au + '?mdu=exchange&ctl=Funds&met=listFundsProfit&typ=json',
		},
		fx: {
			invite: iu + '?ctl=Distribution_User&met=invite&typ=json',
			// "poster": iu + "?ctl=Distribution_User&met=poster&typ=json",
			poster: ip + 'shop/distributionUser/poster',
			// "withdraw": iu + "?ctl=Distribution_User&met=withdraw&typ=json",
			withdraw: ip + 'shop/distributionUser/withdraw',
			//"doWithdraw": iu + "?ctl=Distribution_User&met=doWithdraw&typ=json",
			doWithdraw: ip + 'shop/distributionUser/doWithdraw',
			lists: iu + '?ctl=Distribution_User&met=lists&typ=json',
			// "lists_commission": iu + "?ctl=Distribution_User&met=listsCommission&typ=json",
			lists_commission: ip + 'shop/distributionUser/listsCommission',
			lists_team: iu + '?ctl=Distribution_User&met=listsTeam&typ=json',
			// "lists_order": iu + "?ctl=Distribution_User&met=listsOrder&typ=json",
			lists_order: ip + 'shop/distributionUser/listsOrder',
			// "index":iu + "?ctl=Distribution_User&met=index&typ=json",
			index: ip + 'shop/distributionUser/index',
			// "getCommissionTimeline": iu + "?ctl=Distribution_User&met=getCommissionTimeline&typ=json"
			getCommissionTimeline: ip + 'shop/distributionUser/getCommissionTimeline',
		},
		admin: {
			pay: {
				orderRecord: mu + '?mdu=pay&ctl=Consume_Record&met=orderRecord&typ=json',
				offline: mu + '?mdu=pay&ctl=Consume_Trade&met=offline&typ=json',
			},
			lists: {
				payment_channel: mu + '?ctl=Category&met=lists&typ=json&isDelete=2&type_number=payment_channel_id',
				express: mu + '?ctl=Category&met=lists&typ=json&isDelete=2&type_number=express_id',
			},
		},
		sns: {
			story_timeline_lists: au + '?mdu=sns&ctl=Story_Timeline&met=lists&typ=json',
			// "story_lists": au + "?mdu=sns&ctl=Story&met=lists&typ=json",
			story_lists: ip + 'sns/Story/lists',
			// "story_get": au + "?mdu=sns&ctl=Story&met=get&typ=json",
			story_get: ip + 'sns/Story/getStory',
			//story_add": au + "?mdu=sns&ctl=Story_Base&met=add&typ=json",
			story_add: ip + 'sns/Story/add',
			// story_remove: au + '?mdu=sns&ctl=Story_Base&met=remove&typ=json',// 随商原删除帖子接口
			story_remove: ip + 'sns/Story/remove', // 新帖子接口
			story_edit: au + '?mdu=sns&ctl=Story_Base&met=edit&typ=json',
			// "story_comment_add": au + "?mdu=sns&ctl=Story_Comment&met=add&typ=json",
			story_comment_add: ip + 'sns/Comment/addComment',
			story_comment_remove: au + '?mdu=sns&ctl=Story_Comment&met=remove&typ=json',
			// "story_comment_lists": au + "?mdu=sns&ctl=Story&met=listComment&typ=json",
			story_comment_lists: ip + 'sns/Story/listComment',
			// "story_rel_data": au + "?mdu=sns&ctl=Story&met=getRelData&typ=json",
			story_rel_data: ip + 'sns/Story/getRelData',
			// "category_lists": au + "?mdu=sns&ctl=Story&met=listCategory&typ=json",
			category_lists: ip + 'sns/Story/listCategory',
			// "category_get": au + "?mdu=sns&ctl=Story&met=getCategory&typ=json",
			category_get: ip + 'sns/Story/getCategory',
			// "story_collection_add": au + "?mdu=sns&ctl=Story_Collection&met=add&typ=json",
			story_collection_add: ip + 'sns/collection/add',
			// "story_collection_remove": au + "?mdu=sns&ctl=Story_Collection&met=remove&typ=json",
			story_collection_remove: ip + 'sns/collection/remove',
			// "story_like_add": au + "?mdu=sns&ctl=Story_Like&met=add&typ=json",
			story_like_add: ip + 'sns/Like/add',
			// "story_like_remove": au + "?mdu=sns&ctl=Story_Like&met=remove&typ=json",
			story_like_remove: ip + 'sns/Like/remove',
			// "story_comment_like_add": au + "?mdu=sns&ctl=Story_Comment&met=like&typ=json",
			story_comment_like_add: ip + 'sns/Like/like',
			// "story_comment_like_remove": au + "?mdu=sns&ctl=Story_Comment&met=unlike&typ=json",
			story_comment_like_remove: ip + 'sns/Like/unlike',

			story_comment_reply_like_add: au + '?mdu=sns&ctl=Story_Comment&met=likeReply&typ=json',
			story_comment_reply_like_remove: au + '?mdu=sns&ctl=Story_Comment&met=unlikeReply&typ=json',
			// "user_space": au + "?mdu=sns&ctl=Story&met=space&typ=json",
			user_space: ip + 'sns/Story/space',
			// "user_story": au + "?mdu=sns&ctl=Story&met=story&typ=json",
			user_story: ip + 'sns/Story/story',
			// "user_comment_story": au + "?mdu=sns&ctl=Story&met=listUserCommentStory&typ=json",
			user_comment_story: ip + 'sns/Comment/listUserCommentStory',
			// "user_collect_story": au + "?mdu=sns&ctl=Story&met=listUserCollectStory&typ=json",

			getFriendsInfo: ip + 'sns/userFriend/getFriendsInfo', // 查询关注列表
			user_collect_story: ip + 'sns/Story/listUserCollectStory',
		    getMyMsgNum: ip + 'sns/userMessage/getMyMsgNum',
			setMyMsgNum: ip + 'sns/userMessage/setMyMsgNum',
			roomList: ip + 'sns/userMessage/roomList',

		},
		seller: {
			vehicle_category: mu + '?mdu=&ctl=Base_VehicleCategory&met=tree&typ=json',
			User_Info: mu + '?mdu=account&ctl=User_Info&met=lists&typ=json',
			treeleaf: iu + '?ctl=Product&met=treeleaf&typ=json',
			checkout: mu + '?mdu=seller&ctl=Order_Base&met=checkout&typ=json',
			select_Clerk: mu + '?mdu=seller&ctl=Store_Employee&met=lists&typ=json',
			add_member: mu + '?mdu=invoicing&ctl=Customer_Base&met=add&typ=json',
			product_category: mu + '?mdu=seller&ctl=Base_ProductCategory&met=treeview&typ=json',
			edit_quantity: mu + '?mdu=seller&ctl=Product_Base&met=saveQuantity&typ=json',
			add_DistProduct: mu + '?mdu=&ctl=Product_Base&met=addDistProduct&typ=json',
			// "product_pool": mu + "?mdu=&ctl=Product_Base&met=lists&typ=json",
			product_pool: ip + 'shop/shop-product-base/sellerProductList',
			Order_Base: mu + '?mdu=seller&ctl=Order_Base&met=add&typ=json',
			User_DeliveryAddress: mu + '?mdu=seller&ctl=User_DeliveryAddress&met=lists&typ=json',
			// "store": mu + "?mdu=seller&ctl=Store_Base&met=get&typ=json",
			store: ip + 'shop/store/getStore',
			product: mu + '?mdu=seller&ctl=Product&met=lists&typ=json',
			product_add: mu + '?mdu=seller&ctl=Product&met=add&typ=json',
			add_product: mu + '?mdu=seller&ctl=Product_Base&met=add&typ=json',
			// "get_store_info": mu + "?mdu=seller&ctl=Store_Base&met=get&typ=json",
			get_store_info: ip + 'shop/store/getStore',
			// "edit_store_info": mu + "?mdu=seller&ctl=Store_Base&met=edit&typ=json",
			edit_store_info: ip + 'shop/store/editStore',
			lists_item: mu + '?mdu=seller&ctl=Product_Item&met=lists&typ=json',
			// "lists_product": mu + "?mdu=seller&ctl=Product_Base&met=lists&typ=json",
			lists_product: ip + 'shop/shop-product-base/sellerProductList',
			edit_state: mu + '?mdu=seller&ctl=Product_Base&met=editState&typ=json',
			remove_product: mu + '?mdu=seller&ctl=Product_Base&met=remove&typ=json',
			dashboard: ip + 'shop/store/dashboard',
			// "dashboard": mu + "?mdu=seller&ctl=Index&met=dashboard&typ=json",
			// "order_lists": mu + "?mdu=seller&ctl=Order_Base&met=listsOrderAndsProduct&typ=json",
			order_lists: ip + 'shop/userOrder/listsOrderAndsProduct',
			edit_fee: mu + '?mdu=seller&ctl=Order_Base&met=editFee&typ=json',
			edit_discount: mu + '?mdu=seller&ctl=Order_Base&met=editDiscount&typ=json',
			review: mu + '?mdu=seller&ctl=Order_Base&met=review&typ=json',
			review_finance: mu + '?mdu=seller&ctl=Order_Base&met=reviewFinance&typ=json',
			review_picking: mu + '?mdu=seller&ctl=Order_Base&met=reviewPicking&typ=json',
			cancel_order: mu + '?mdu=seller&ctl=Order_Base&met=cancel&typ=json',
			getOrderStock: mu + '?mdu=seller&ctl=Order_Base&met=getOrderStock&typ=json',
			saveOrderLogistics: mu + '?mdu=seller&ctl=Order_Base&met=saveOrderLogistics&typ=json',
			// "lists_shipping_address": mu + "?mdu=seller&ctl=Store_ShippingAddress&met=lists&typ=json",
			lists_shipping_address: ip + 'shop/store/getAddressList',
			// "del_shipping_address": mu + "?mdu=seller&ctl=Store_ShippingAddress&met=remove&typ=json",
			// "add_shipping_address": mu + "?mdu=seller&ctl=Store_ShippingAddress&met=add&typ=json",
			// "edit_shipping_address": mu + "?mdu=seller&ctl=Store_ShippingAddress&met=edit&typ=json",
			// "get_shipping_address": mu + "?mdu=seller&ctl=Store_ShippingAddress&met=get&typ=json",
			del_shipping_address: ip + 'shop/store/delAddress',
			add_shipping_address: ip + 'shop/store/editAddress',
			edit_shipping_address: ip + 'shop/store/editAddress',
			get_shipping_address: ip + 'shop/store/getAddress',
			get_express_logistics: mu + '?mdu=seller&ctl=Store_ExpressLogistics&met=get&typ=json',
			select_express_logistics: mu + '?mdu=seller&ctl=Store_ExpressLogistics&met=selectDefault&typ=json',
			// "enabled_express_logistics": mu + "?mdu=seller&ctl=Store_ExpressLogistics&met=selectEnabled&typ=json",
			enabled_express_logistics: ip + 'shop/store/selectEnabled',
			// "lists_express_logistics": mu + "?mdu=seller&ctl=Store_ExpressLogistics&met=lists&typ=json",
			lists_express_logistics: ip + 'shop/store/expressLogistics',
			del_express_logistics: mu + '?mdu=seller&ctl=Store_ExpressLogistics&met=remove&typ=json',
			add_express_logistics: mu + '?mdu=seller&ctl=Store_ExpressLogistics&met=add&typ=json',
			edit_express_logistics: mu + '?mdu=seller&ctl=Store_ExpressLogistics&met=edit&typ=json',
			order_cancel: mu + '?mdu=seller&ctl=Order_Base&met=cancel&typ=json',
			order_receive: mu + '?mdu=seller&ctl=Order_Base&met=receive&typ=json',
			order_remove: mu + '?mdu=seller&ctl=Order_Base&met=remove&typ=json',
			order_detail: mu + '?mdu=seller&ctl=Order_Base&met=detail&typ=json',
			// "order_get_by_pickupcode": mu + "?mdu=seller&ctl=Order_Base&met=getOrderByPickUpCode&typ=json",
			order_get_by_pickupcode: ip + 'shop/userOrder/getOrderByPickUpCode',
			do_pickup: mu + '?mdu=seller&ctl=Order_Base&met=doPickUp&typ=json',
			order_delivery: mu + '?mdu=seller&ctl=Order_Base&met=delivery&typ=json',
			market_lists: mu + '?mdu=city&ctl=Market_OrderBase&met=lists&typ=json',
			waybill_tpl_lists: mu + '?mdu=seller&ctl=Store_WaybillTpl&met=lists&typ=json',
			waybill_tpl_add: mu + '?mdu=seller&ctl=Store_WaybillTpl&met=add&typ=json',
			// "express_logistics_lists": mu + "?mdu=seller&ctl=Store_ExpressLogistics&met=lists&typ=json",
			express_logistics_lists: ip + 'shop/store/expressLogistics',
			express_logistics_add: mu + '?mdu=seller&ctl=Store_ExpressLogistics&met=add&typ=json',
			// "shipping_address_lists": mu + "?mdu=seller&ctl=Store_ShippingAddress&met=lists&typ=json",
			shipping_address_lists: ip + 'shop/store/getAddressList',
			shipping_address_add: mu + '?mdu=seller&ctl=Store_ShippingAddress&met=add&typ=json',
			add_store_book: mu + '?mdu=seller&ctl=Store_Book&met=add&typ=json',
			lists_store_book: mu + '?mdu=seller&ctl=Store_Book&met=lists&typ=json',
			del_store_book: mu + '?mdu=seller&ctl=Store_Book&met=remove&typ=json',
			edit_store_book: mu + '?mdu=seller&ctl=Store_Book&met=edit&typ=json',
			// "getOrderDetail": mu + "?mdu=seller&ctl=Order_Base&met=getOrderDetail&typ=json",
			getOrderDetail: ip + 'shop/userOrder/getOrderDetail',
			multiUpload: mu + '?mdu=seller&ctl=Order_Item&met=multiUpload&typ=json',
			Store_TransportType: mu + '?mdu=seller&ctl=Store_TransportType&met=lists&typ=json',
			Store_ProductCategory: mu + '?mdu=seller&ctl=Store_ProductCategory&met=treeview&typ=json',
		},
		city: {
			// "paotui_info": iu + "?mdu=city&ctl=User_Paotuier&met=info&typ=json",
			paotui_info: ip + 'shop/userPaotuier/info',
			// "paotui_active": iu + "?mdu=city&ctl=User_Paotuier&met=setActive&typ=json",
			paotui_active: ip + 'shop/userPaotuier/setActive',
			paotui_apply: iu + '?mdu=city&ctl=User_Paotuier&met=add&typ=json',
			// "paotui_order_list": iu + "?mdu=city&ctl=User_Paotuier&met=getOrderList&typ=json",
			paotui_order_list: ip + 'shop/userPaotuier/getOrderList',
			paotui_finish_order: iu + '?mdu=city&ctl=User_Paotuier&met=getFinishOrderList&typ=json',
			// "paotui_certificate": iu + "?mdu=city&ctl=User_Paotuier&met=saveCertificate&typ=json",
			paotui_certificate: ip + 'shop/userPaotuier/saveCertificate',
			team_add: iu + '?mdu=city&ctl=Paotui_Team&met=add&typ=json',
			order_add: iu + '?mdu=city&ctl=Paotui_Order&met=add&typ=json',
			// "order_lists": iu + "?mdu=city&ctl=Paotui_Order&met=lists&typ=json",
			order_lists: ip + 'shop/paotuierOrder/lists',
			order_apply: iu + '?mdu=city&ctl=Paotui_Order&met=apply&typ=json',
			order_pickup: iu + '?mdu=city&ctl=Paotui_Order&met=pickup&typ=json',
			order_signin: iu + '?mdu=city&ctl=Paotui_Order&met=signin&typ=json',
			// "order_get": iu + "?mdu=city&ctl=Paotui_Order&met=get&typ=json",
			order_get: iu + 'shop/paotuierOrder/get',
			order_remove: iu + '?mdu=city&ctl=Paotui_Order&met=remove&typ=json',
			receive_order: mu + '?mdu=city&ctl=Market_OrderBase&met=getMarketOrder&typ=json',
			confirm_receive: mu + '?mdu=city&ctl=Market_OrderBase&met=enable&typ=json',
			store_Base_list: mu + '?ctl=Store_Base&met=lists&typ=json',
			transfer_market_order: mu + '?mdu=seller&ctl=Order_Base&met=transferMarketOrder&typ=json',
			upload_images: mu + '?mdu=seller&ctl=Order_Item&met=updateItemFile&typ=json',
		},
		hall: {
			//start 采购大厅
			// "purchase_order_lists": iu + "?mdu=hall&ctl=Purchase_OrderBase&met=lists&typ=json",
			purchase_order_lists: ip + 'shop/purchase/lists',
			get_purchase_order_Detail: iu + '?mdu=hall&ctl=Purchase_OrderBase&met=get&typ=json',
			save_purchase_order: iu + '?mdu=hall&ctl=Purchase_OrderBase&met=save&typ=json',

			// "user_purchase_order_lists":iu + "?mdu=hall&ctl=User_Purchase&met=listPurchaseOrder&typ=json",
			user_purchase_order_lists: ip + 'shop/purchase/listPurchaseOrder',
			user_purchase_order: iu + '?mdu=hall&ctl=User_Purchase&met=save&typ=json',
			// "user_purchase_order_get":iu + "?mdu=hall&ctl=User_Purchase&met=get&typ=json",
			user_purchase_order_get: ip + 'shop/purchase/get',
			// "user_purchase_order_index": iu + "?mdu=hall&ctl=User_Purchase&met=index&typ=json",
			user_purchase_order_index: ip + 'shop/purchase/index',
			// "remove_purchase_order": iu + "?mdu=hall&ctl=User_Purchase&met=remove&typ=json",
			remove_purchase_order: ip + 'shop/purchase/remove',
			user_purchase_order_cancel: iu + '?mdu=hall&ctl=User_Purchase&met=cancelOrder&typ=json',
			user_purchase_select_supply: iu + '?mdu=hall&ctl=User_Purchase&met=selectSupplyOrder&typ=json',
			user_purchase_order_check_do: iu + '?mdu=hall&ctl=User_Purchase&met=doOrderCheck&typ=json',

			supply_order_lists: iu + '?mdu=hall&ctl=Supply_OrderBase&met=lists&typ=json',

			supply_order_add: iu + '?mdu=hall&ctl=User_Supply&met=addOrder&typ=json',
			supply_order_check_add: iu + '?mdu=hall&ctl=User_Supply&met=applyOrderCheck&typ=json',
			// "user_supply_order_lists": iu + "?mdu=hall&ctl=User_Supply&met=listSupplyOrder&typ=json",
			user_supply_order_lists: ip + 'shop/supply/listSupplyOrder',
			//end 采购大厅

			service_order_lists: iu + '?mdu=hall&ctl=Service_OrderBase&met=lists&typ=json',
			getOrderDetail: iu + '?mdu=hall&ctl=Service_OrderBase&met=get&typ=json',

			user_service_order_lists: iu + '?mdu=hall&ctl=User_Service&met=listServiceOrder&typ=json',
			user_service_order_cancel: iu + '?mdu=hall&ctl=User_Service&met=cancelOrder&typ=json',
			user_service_select_worker: iu + '?mdu=hall&ctl=User_Service&met=selectWorkerOrder&typ=json',
			user_service_order_check_do: iu + '?mdu=hall&ctl=User_Service&met=doOrderCheck&typ=json',

			worker_order_lists: iu + '?mdu=hall&ctl=Worker_OrderBase&met=lists&typ=json',

			worker_order_add: iu + '?mdu=hall&ctl=User_Worker&met=addOrder&typ=json',
			worker_order_check_add: iu + '?mdu=hall&ctl=User_Worker&met=applyOrderCheck&typ=json',
			user_worker_order_lists: iu + '?mdu=hall&ctl=User_Worker&met=listWorkerOrder&typ=json',

			index: iu + '?mdu=hall&ctl=Index&met=index&typ=e',
			orderForIndex: iu + '?mdu=hall&ctl=Index&met=orderForIndex&typ=e',
			member: iu + '?mdu=hall&ctl=Index&met=member&typ=e',
			workerHome: iu + '?mdu=hall&ctl=User_Worker&met=home&typ=e',
			postAddress: iu + '?mdu=hall&ctl=User_Invoice&met=postAddress&typ=e',
			companyIndex: iu + '?mdu=hall&ctl=User_Company&met=index&typ=e',
			companyOrder: iu + '?mdu=hall&ctl=User_Company&met=order&typ=e',
			companyPayment: iu + '?mdu=hall&ctl=Service_OrderBase&met=payment&typ=e',
			companyPaymentSuccess: iu + '?mdu=hall&ctl=Service_OrderBase&met=paymentSuccess&typ=e',
			companyInfo: iu + '?mdu=hall&ctl=User_Company&met=info&typ=e',
			workerIndex: iu + '?mdu=hall&ctl=User_Worker&met=index&typ=e',
			workerOrder: iu + '?mdu=hall&ctl=User_Worker&met=order&typ=e',
			workerInfo: iu + '?mdu=hall&ctl=User_Worker&met=info&typ=e',
			orderManage: iu + '?mdu=hall&ctl=Service_OrderBase&met=manage&typ=e',
			workerComment: iu + '?mdu=hall&ctl=User_Worker&met=comment&typ=e',
			companyComment: iu + '?mdu=hall&ctl=User_Company&met=comment&typ=e',
			orderDetail: iu + '?mdu=hall&ctl=Service_OrderBase&met=orderDetail&typ=e',
			editBankCard: iu + '?mdu=hall&ctl=User_BankCard&met=editBankCard&typ=e',
			delBankCard: iu + '?mdu=hall&ctl=User_BankCard&met=delBankCard&typ=json',
			myBankCard: iu + '?mdu=hall&ctl=User_BankCard&met=myBankCard&typ=e',
			getBankList: iu + '?mdu=hall&ctl=User_BankCard&met=getBankList&typ=json',
			getUserBankList: iu + '?mdu=hall&ctl=User_BankCard&met=getUserBankList&typ=json',
			saveBankCardInfo: iu + '?mdu=hall&ctl=User_BankCard&met=saveBankCardInfo&typ=json',
			getTheBankCardInfo: iu + '?mdu=hall&ctl=User_BankCard&met=getTheBankCardInfo&typ=json',
			isLogin: iu + '?mdu=hall&ctl=Index&met=isHallLogin&typ=json',
			getCity: iu + '?mdu=hall&ctl=Index&met=getCity&typ=json',
			scrollPic: iu + '?mdu=hall&ctl=Index&met=scrollPic&typ=json',
			getStars: iu + '?mdu=hall&ctl=Index&met=getStars&typ=json',
			getCompanyInfo: iu + '?mdu=hall&ctl=User_Company&met=getCompanyInfo&typ=json',
			getCodeList: iu + '?mdu=hall&ctl=Index&met=getCodeList&typ=json',
			saveCompanyValidate: iu + '?mdu=hall&ctl=User_Company&met=saveCompanyValidate&typ=json',
			saveCompanyInfo: iu + '?mdu=hall&ctl=User_Company&met=saveCompanyInfo&typ=json',
			isValidateIdentity: iu + '?mdu=hall&ctl=Index&met=isValidateIdentity&typ=json',
			savePersonValidate: iu + '?mdu=hall&ctl=User_Worker&met=savePersonValidate&typ=json',
			getAuthorizeSign: iu + '?mdu=hall&ctl=User_Worker&met=getAuthorizeSign&typ=json',
			getSkill: iu + '?mdu=hall&ctl=User_Worker&met=getSkill&typ=json',
			completePersonInfo: iu + '?mdu=hall&ctl=User_Worker&met=completePersonInfo&typ=json',
			saveServiceOrderInfo: iu + '?mdu=hall&ctl=Service_OrderBase&met=saveServiceOrderInfo&typ=json',
			add_service_order: iu + '?mdu=hall&ctl=Service_OrderBase&met=add&typ=json',
			orderListPartial: iu + '?mdu=hall&ctl=Service_OrderBase&met=orderListPartial&typ=json',
			orderListPartialForCompany: iu + '?mdu=hall&ctl=User_Company&met=orderListPartial&typ=json',
			orderListPartialForWorker: iu + '?mdu=hall&ctl=User_Worker&met=orderListPartial&typ=e',
			getOrder: iu + '?mdu=hall&ctl=Service_OrderBase&met=getOrder&typ=json',
			getUserInfo: iu + '?mdu=hall&ctl=User_Worker&met=getUserInfo&typ=json',
			addService: iu + '?mdu=hall&ctl=User_Service&met=add&typ=json',
			editService: iu + '?mdu=hall&ctl=User_Service&met=edit&typ=json',
			getService: iu + '?mdu=hall&ctl=User_Service&met=get&typ=json',
			delService: iu + '?mdu=hall&ctl=User_Service&met=remove&typ=json',
			myServiceListPartial: iu + '?mdu=hall&ctl=User_Service&met=lists&typ=json',
			checkSignUp: iu + '?mdu=hall&ctl=Index&met=checkSingUp&typ=json',
			getListByCate: iu + '?mdu=hall&ctl=Index&met=getListByCate&typ=json',
			getHomeData: iu + '?mdu=hall&ctl=Index&met=getHomeData&typ=json',
			serviceListPartial: iu + '?mdu=hall&ctl=Index&met=serviceListPartial&typ=json',
			getOrderList: iu + '?mdu=hall&ctl=Index&met=orderForIndex&typ=json',
			//"getOrderDetail":iu + "?mdu=hall&ctl=Service_OrderBase&met=order&typ=json",
			getWorkerStudio: iu + '?mdu=hall&ctl=Worker_Studio&met=lists&typ=json',
			checkTax: iu + '?mdu=hall&ctl=Index&met=checkTax&typ=json',
			signUpListPartial: iu + '?mdu=hall&ctl=Index&met=signUpListPartial&typ=e',
			saveSignUp: iu + '?mdu=hall&ctl=Index&met=saveSignUp&typ=json',
			checkChoose: iu + '?mdu=hall&ctl=Index&met=checkChoose&typ=json',
			cancelSign: iu + '?mdu=hall&ctl=User_Worker&met=cancelSign&typ=json',
			newBalancePay: iu + '?mdu=hall&ctl=User_Company&met=newBalancePay&typ=json',
			countTime: iu + '?mdu=hall&ctl=User_Worker&met=countTime&typ=json',
			requestedChange: iu + '?mdu=hall&ctl=User_Worker&met=requestedChange&typ=json',
			submitCheck: iu + '?mdu=hall&ctl=User_Worker&met=submitCheck&typ=json',
			getSignUpInfo: iu + '?mdu=hall&ctl=User_Company&met=getSignUpInfo&typ=json',
			getSignWorker: iu + '?mdu=hall&ctl=User_Company&met=getSignWorker&typ=json',
			getUserBank: iu + '?mdu=hall&ctl=User_Invoice&met=getUserBank&typ=json',
			savePostAddress: iu + '?mdu=hall&ctl=User_Invoice&met=savePostAddress&typ=json',
			getPostAddress: iu + '?mdu=hall&ctl=User_Invoice&met=getPostAddress&typ=json',
			delPostAddress: iu + '?mdu=hall&ctl=User_Invoice&met=delPostAddress&typ=json',
			saveEmail: iu + '?mdu=hall&ctl=User_Invoice&met=saveEmail&typ=json',
			getEmail: iu + '?mdu=hall&ctl=User_Invoice&met=getEmail&typ=json',
			delEmail: iu + '?mdu=hall&ctl=User_Invoice&met=delEmail&typ=json',
			getAddress: iu + '?mdu=hall&ctl=User_Invoice&met=getAddress&typ=json',
			getAddressByOne: iu + '?mdu=hall&ctl=User_Invoice&met=getAddressByOne&typ=json',
			getEmails: iu + '?mdu=hall&ctl=User_Invoice&met=getEmails&typ=json',
			newSubmitQualified: iu + '?mdu=hall&ctl=User_Company&met=newSubmitQualified&typ=json',
			newSubmitQuaItem: iu + '?mdu=hall&ctl=User_Company&met=newSubmitQuaItem&typ=json',
			saveJudgeLevelByCompany: iu + '?mdu=hall&ctl=User_Company&met=saveJudgeLevel&typ=json',
			saveJudgeLevelByWorker: iu + '?mdu=hall&ctl=User_Worker&met=saveJudgeLevel&typ=json',
			getUserBlanceByNo: iu + '?mdu=hall&ctl=User_Resource&met=getUserBalanceByNo&typ=json',
			systemMessage: au + '?mdu=sns&ctl=User_Message&met=index&typ=e',
			getBillsList: iu + '?mdu=hall&ctl=User_Bill&met=index&typ=json',
			setDefaultPostAddress: iu + '?mdu=hall&ctl=User_Invoice&met=setDefaultPostAddress&typ=json',
			saveUserBank: iu + '?mdu=hall&ctl=User_Invoice&met=saveUserBank&typ=json',
			getServiceListForSale: iu + '?mdu=hall&ctl=User_Invoice&met=getServiceListForSale&typ=json',
			getServiceInfo: iu + '?mdu=hall&ctl=User_Service&met=getServiceInfo&typ=json',
			addServiceOrder: iu + '?mdu=hall&ctl=User_Service&met=addServiceOrder&typ=json',
			register: bu + '?mdu=account&ctl=Login&met=register&typ=e',
			studioLookup: iu + '?mdu=hall&ctl=Worker_Studio&met=studioLookup&typ=json',
			studioNum: iu + '?mdu=hall&ctl=Worker_Studio&met=studioNum&typ=json',
		},
		live: {
			//"checkPerm": "https://test.suteshop.com/index.php?mdu=live&ctl=Live&met=checkPerm&typ=json",
			checkPerm: ip + 'sns/Live/checkPerm',
			//"saveRoom": "https://test.suteshop.com/index.php?mdu=live&ctl=Live&met=saveRoom&typ=json",
			saveRoom: ip + 'sns/Live/saveRoom',
			// "index": iu + "?mdu=live&ctl=Live&met=index&typ=json",
			index: ip + 'sns/Live/index',
			rtc: bu + '/shop/api/rtc.php',

			createRoom: iu + '?mdu=live&ctl=WeixinLive&met=createRoom&typ=json',
			listRoom: iu + '?mdu=live&ctl=WeixinLive&met=listRoom&typ=json',
		},
		edu: {
			//讲师
			getLectureList: ip + 'edu/edu-user-lecturer/getLecturerList',
			getLecturerDetail: ip + 'edu/edu-user-lecturer/getLecturerDetail',
			subscribeLecturer: ip + 'edu/edu_subscribe_lecturer/subscribeLecturer',
			isSubscribe: ip + 'edu/edu_subscribe_lecturer/isSubscribe',
			//班期
			getCycleList: ip + 'edu/edu-classes-cycle/getCycleList',
			getCycle: ip + 'edu/edu-classes-cycle/getCycle',
			isJoinCycle: ip + 'edu/edu-classes-cycle/isJoinCycle',
			//考试
			getExamList: ip + 'edu/edu-exam-base/list',
			isCanDoExam: ip + 'edu/edu-exam-base/isCanDoExam',
			getCategoryAndTopicNum: ip + 'edu/edu-topic-category/getCategoryAndTopicNum',
			getListByChapter: ip + 'edu/edu-paper-base/list',
			getExamByClassesId: ip + 'edu/edu-exam-base/getExamByClassesId',
			getTopicListByPaperId: ip + 'edu/edu-topic-base/getTopicListByPaperId',
			saveExam: ip + 'edu/edu-exam-base/saveExam',
			getRgihtVal: ip + 'edu/edu-topic-base/getRgihtVal',
			getPaperList: ip + 'edu/edu-paper-base/list',
			getCourseCert: ip + 'edu/course/getCourse',
			getUserExamList: ip + 'edu/edu-user-paper-info/list',
			//证书
			getUserCert: ip + 'edu/edu-user-cert/getUserCert',
			//课程
			getCategoryList: ip + 'edu/course/getCategoryList',
			getCourseList: ip + 'shop/shop-product-item/getCourseList',
			getCourse: ip + 'shop/shop-product-item/getCourse',
			getProduct: ip + 'shop/shop-product-item/getProduct',
			getProductList: ip + 'shop/shop-product-base/lists',
			getProductItem: ip + 'shop/shop-product-item/item',
			order_add: ip + 'shop/userOrder/add',
			saveChapterStock: ip + 'edu/chapterSock/saveChapterStock',
			getBuyCourseList: ip + 'edu/courseStock/getBuyCourseList',
			getDiploma: ip + 'edu/course/getDiploma',
			getAdmissionNotice: ip + 'edu/course/getAdmissionNotice',
			getTeacherQrcode: ip + 'edu/course/getTeacherQrcode',
			setLearnTarget: ip + 'edu/learnTarget/setLearnTarget',
			getLearnTarget: ip + 'edu/learnTarget/getLearnTarget',
			getLearnTime: ip + 'edu/learnTarget/getLearnTime',
			saveCourseStock: ip + 'edu/courseStock/saveCourseStock',
			getCourseContract: ip + 'edu/course/getCourseContract',
			getChapter: ip + 'edu/course/getChapter',
			userAddClass: ip + 'edu/edu-classes-cycle/userAddClass',
		},
	},
	tabBar: {
		color: '#7A7E83',
		borderStyle: 'black',
		backgroundColor: '#ffffff',

		selectedColor: '#DB384C',
		list: [{
				pagePath: 'pages/index/index',
				iconPath: 'static/images/tabBar1.png',
				selectedIconPath: 'static/images/tabBar_sel1.png',
				text: '首页',
			},
			{
				pagePath: 'pages/index/image',
				iconPath: 'static/images/tabBar2.png',
				selectedIconPath: 'static/images/tabBar_sel2.png',
				text: '发现',
			},
			{
				pagePath: 'pages/course/study',
				iconPath: 'static/images/tabBar3.png',
				selectedIconPath: 'static/images/tabBar_sel3.png',
				text: '学习',
			},
			{
				pagePath: 'pages/index/member',
				iconPath: 'static/images/tabBar4.png',
				selectedIconPath: 'static/images/tabBar_sel4.png',
				text: '个人',
			},
		],
	},
};
